---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-app
  namespace: mcp
  labels:
    app: contract-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-app
  template:
    metadata:
      labels:
        app: contract-app
    spec:
      serviceAccountName: ${PRODUCT_NAME}-sa
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: contract-app
          image: $ECR_REPOSITORY:$PRODUCT_VERSION # Change the value here
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contract-service
  namespace: mcp
spec:
  type: NodePort
  selector:
    app: contract-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
