Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
Resources:
  meterusagepol:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: meteringactions
            Effect: Allow
            Action:
              - aws-marketplace:registerUsage
              - aws-marketplace:RegisterUsage
            Resource: '*'
Outputs:
  meterusagepolarn:
    Value: !Ref meterusagepol