---
kind: Namespace
apiVersion: v1
metadata:
  name: mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registerusage-app
  labels:
    app: registerusage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registerusage-app
  template:
    metadata:
      labels:
        app: registerusage-app
    spec:
      serviceAccountName: awsome-mp-product-sa
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: registerusage-app
          image: 987961232451.dkr.ecr.us-east-1.amazonaws.com/awsome-mp-product:usage_3 # Change the value here
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registerusage-service
spec:
  selector:
    app: registerusage-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: registerusage-ingress
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
    labels:
        app: registerusage-app
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: registerusage-service
              port:
                number: 80